# ==============================================================================
# Simulation Script: tb_ml_kem_top  (POST-SYNTHESIS FUNCTIONAL)
# ==============================================================================
# Runs the same KAT vec #0 regression as sim_tb_ml_kem_top.tcl, but on the
# *synthesized netlist* instead of behavioral RTL. If this fails the same way
# the on-board bitstream does, the bug was introduced by synthesis (e.g. ROM
# INIT lost, optimization removed something). If this passes, the bug is in
# implementation/timing.
# ==============================================================================
# CLEANUP (if locked): taskkill /F /IM xsimk.exe /T & taskkill /F /IM xsim.exe /T & taskkill /F /IM vivado.bat /T & taskkill /F /IM vivado.exe /T
#
# PRE-REQUISITE: KAT0 .mem files (already generated by extract_kat0.py)
#
# EXECUTION (CMD):
#   cd /d D:\HCMUT\Year_4\252\CA\Source\DACN && "C:\Xilinx\2025.1\Vivado\bin\vivado.bat" -mode batch -source verilog_ML_KEM/scripts/AXI/sim_postsynth_tb_ml_kem_top.tcl -tclargs D:/HCMUT/Year_4/252/CA/Vivado/verilog_ML_KEM/verilog_ML_KEM.xpr
# ==============================================================================

if {[llength $argv] < 1} {
    puts "ERROR: Missing project path argument"
    puts "Usage: vivado -mode batch -source sim_postsynth_tb_ml_kem_top.tcl -tclargs <xpr_path>"
    exit 1
}

set xpr_path [file normalize [lindex $argv 0]]
set script_dir [file dirname [file normalize [info script]]]
set base_out_dir [file join $script_dir "tb_ml_kem_top_metrics"]
set ts [clock format [clock seconds] -format "%Y%m%d_%H%M%S"]
set run_dir [file join $base_out_dir "postsynth_$ts"]

file mkdir $run_dir
cd $run_dir
puts "INFO: Running post-synth simulation in: $run_dir"

open_project $xpr_path

# Make sure synth_1 is up to date — open_run forces synth if needed
if {[get_property STATUS [get_runs synth_1]] ne "synth_design Complete!"} {
    puts "INFO: synth_1 not complete, launching synthesis..."
    reset_run synth_1
    launch_runs synth_1 -jobs 8
    wait_on_run synth_1
}

if {[llength [current_sim -quiet]] > 0} {
    puts "INFO: Closing previous simulation session..."
    close_sim -force
}

set_property top tb_ml_kem_top [get_filesets sim_1]
update_compile_order -fileset sim_1
set_property xsim.simulate.runtime all [get_filesets sim_1]

# Switch sim mode to post-synthesis functional
set_property -name {xsim.elaborate.debug_level} -value {typical} -objects [get_filesets sim_1]

set launched 0
set launch_err ""
for {set t 0} {$t < 5} {incr t} {
    if {$t > 0} {
        puts "RETRY: Resetting simulation state ($t)..."
        reset_simulation -simset sim_1 -mode post-synthesis -type functional
    }
    if {[catch {launch_simulation -simset sim_1 -mode post-synthesis -type functional} launch_err]} {
        after 2000
    } else {
        set launched 1
        break
    }
}

if {!$launched} {
    puts "ERROR: launch_simulation failed after retries."
    puts "DETAIL: $launch_err"
    close_project
    exit 5
}

# 3. Run and analyze
set xsim_log [file normalize [file join [get_property DIRECTORY [current_project]] "[get_property NAME [current_project]].sim" "sim_1" "synth" "func" "xsim" "simulate.log"]]
catch {close_sim -force}

if {![file exists $xsim_log]} {
    puts "ERROR: simulate.log not found at $xsim_log"
    close_project
    exit 2
}

file copy -force $xsim_log [file join $run_dir "tb_ml_kem_top_postsynth_simulate.log"]

set fp [open [file join $run_dir "tb_ml_kem_top_postsynth_simulate.log"] r]
set log_txt [read $fp]
close $fp

set must_have [list \
    "Gate B KAT KeyGen: pk + sk match (vec #0)" \
    "Gate B KAT Encaps: ct + ss match (vec #0)" \
    "Gate B KAT Decaps: ss match (vec #0)" \
    "tb_ml_kem_top: PASS"]

set must_not_have [list \
    "KAT KeyGen pk mismatch" \
    "KAT KeyGen sk mismatch" \
    "KAT Encaps ct mismatch" \
    "KAT Encaps ss mismatch" \
    "KAT Decaps ss mismatch" \
    "TIMEOUT" \
    "\$fatal" \
    "\$stop called"]

set found_fail 0
foreach p $must_not_have {
    if {[string first $p $log_txt] >= 0} {
        puts "POST-SYNTH FAIL: hit failure marker: $p"
        set found_fail 1
    }
}

if {$found_fail} {
    puts ""
    puts "=========================================================="
    puts "VERDICT: Synthesis introduces the bug."
    puts "  RTL behavioral sim:   PASS  (already verified)"
    puts "  Post-synth func sim:  FAIL  (this run)"
    puts "  -> The synth_design step corrupts the design."
    puts "     Inspect ROM INIT, removed cells, optimization warnings."
    puts "=========================================================="
    puts "INFO: full log -> [file join $run_dir tb_ml_kem_top_postsynth_simulate.log]"
    close_project
    exit 4
}

foreach p $must_have {
    if {[string first $p $log_txt] < 0} {
        puts "POST-SYNTH FAIL: missing PASS marker: $p"
        puts "INFO: full log -> [file join $run_dir tb_ml_kem_top_postsynth_simulate.log]"
        close_project
        exit 3
    }
}

puts ""
puts "=========================================================="
puts "VERDICT: Synthesis is clean."
puts "  RTL behavioral sim:   PASS"
puts "  Post-synth func sim:  PASS  (this run)"
puts "  -> Bug is in IMPLEMENTATION (placement/routing/timing)."
puts "     Next: run post-impl timing sim or inspect timing reports"
puts "     and BUFG/clock distribution differences."
puts "=========================================================="
puts "INFO: All outputs located in $run_dir"
close_project
exit 0
